Repository kubesphere/s2irun, pull requests merged in 2019-10, with the labels that each got.

#14 improve log level
  pkg/docker/docker.go
Labels: approved, lgtm, size/XS

#15 log with s2irun url
  pkg/errors/errors.go
Labels: approved, size/XS

#16 add jenkinsfile
  Jenkinsfile
  OWNERS
Labels: approved, lgtm, size/M
